/**
 * Enterprise Reporting v3 APIs (preview)
 * The Reporting APIs enable Enterprise Azure customers to programmatically pull consumption and billing data into preferred data analysis tools. Generate API Key on Enterprise portal and follow the tutorial under Help - Reporting APIs. The first section under this help article explains how to generate\\retrieve the API key for the specified enrollment. <a href=\"https://docs.microsoft.com/en-us/azure/billing/billing-enterprise-api\" data-linktype=\"external\">Billing Enterprise API official documentation</a>
 *
 * OpenAPI spec version: v3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EnterpriseReportingV3ApIsPreview) {
      root.EnterpriseReportingV3ApIsPreview = {};
    }
    root.EnterpriseReportingV3ApIsPreview.UsageDetailsDeNormalizedTitaniumJuly = factory(root.EnterpriseReportingV3ApIsPreview.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The UsageDetailsDeNormalizedTitaniumJuly model module.
   * @module model/UsageDetailsDeNormalizedTitaniumJuly
   * @version v3
   */

  /**
   * Constructs a new <code>UsageDetailsDeNormalizedTitaniumJuly</code>.
   * @alias module:model/UsageDetailsDeNormalizedTitaniumJuly
   * @class
   */
  var exports = function() {
    var _this = this;









































  };

  /**
   * Constructs a <code>UsageDetailsDeNormalizedTitaniumJuly</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UsageDetailsDeNormalizedTitaniumJuly} obj Optional instance to populate.
   * @return {module:model/UsageDetailsDeNormalizedTitaniumJuly} The populated <code>UsageDetailsDeNormalizedTitaniumJuly</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('serviceName')) {
        obj['serviceName'] = ApiClient.convertToType(data['serviceName'], 'String');
      }
      if (data.hasOwnProperty('serviceTier')) {
        obj['serviceTier'] = ApiClient.convertToType(data['serviceTier'], 'String');
      }
      if (data.hasOwnProperty('location')) {
        obj['location'] = ApiClient.convertToType(data['location'], 'String');
      }
      if (data.hasOwnProperty('chargesBilledSeparately')) {
        obj['chargesBilledSeparately'] = ApiClient.convertToType(data['chargesBilledSeparately'], 'Boolean');
      }
      if (data.hasOwnProperty('partNumber')) {
        obj['partNumber'] = ApiClient.convertToType(data['partNumber'], 'String');
      }
      if (data.hasOwnProperty('resourceGuid')) {
        obj['resourceGuid'] = ApiClient.convertToType(data['resourceGuid'], 'String');
      }
      if (data.hasOwnProperty('offerId')) {
        obj['offerId'] = ApiClient.convertToType(data['offerId'], 'String');
      }
      if (data.hasOwnProperty('cost')) {
        obj['cost'] = ApiClient.convertToType(data['cost'], 'Number');
      }
      if (data.hasOwnProperty('accountId')) {
        obj['accountId'] = ApiClient.convertToType(data['accountId'], 'Number');
      }
      if (data.hasOwnProperty('productId')) {
        obj['productId'] = ApiClient.convertToType(data['productId'], 'Number');
      }
      if (data.hasOwnProperty('resourceLocationId')) {
        obj['resourceLocationId'] = ApiClient.convertToType(data['resourceLocationId'], 'Number');
      }
      if (data.hasOwnProperty('consumedServiceId')) {
        obj['consumedServiceId'] = ApiClient.convertToType(data['consumedServiceId'], 'Number');
      }
      if (data.hasOwnProperty('departmentId')) {
        obj['departmentId'] = ApiClient.convertToType(data['departmentId'], 'Number');
      }
      if (data.hasOwnProperty('accountOwnerEmail')) {
        obj['accountOwnerEmail'] = ApiClient.convertToType(data['accountOwnerEmail'], 'String');
      }
      if (data.hasOwnProperty('accountName')) {
        obj['accountName'] = ApiClient.convertToType(data['accountName'], 'String');
      }
      if (data.hasOwnProperty('serviceAdministratorId')) {
        obj['serviceAdministratorId'] = ApiClient.convertToType(data['serviceAdministratorId'], 'String');
      }
      if (data.hasOwnProperty('subscriptionId')) {
        obj['subscriptionId'] = ApiClient.convertToType(data['subscriptionId'], 'Number');
      }
      if (data.hasOwnProperty('subscriptionGuid')) {
        obj['subscriptionGuid'] = ApiClient.convertToType(data['subscriptionGuid'], 'String');
      }
      if (data.hasOwnProperty('subscriptionName')) {
        obj['subscriptionName'] = ApiClient.convertToType(data['subscriptionName'], 'String');
      }
      if (data.hasOwnProperty('date')) {
        obj['date'] = ApiClient.convertToType(data['date'], 'Date');
      }
      if (data.hasOwnProperty('product')) {
        obj['product'] = ApiClient.convertToType(data['product'], 'String');
      }
      if (data.hasOwnProperty('meterId')) {
        obj['meterId'] = ApiClient.convertToType(data['meterId'], 'String');
      }
      if (data.hasOwnProperty('meterCategory')) {
        obj['meterCategory'] = ApiClient.convertToType(data['meterCategory'], 'String');
      }
      if (data.hasOwnProperty('meterSubCategory')) {
        obj['meterSubCategory'] = ApiClient.convertToType(data['meterSubCategory'], 'String');
      }
      if (data.hasOwnProperty('meterRegion')) {
        obj['meterRegion'] = ApiClient.convertToType(data['meterRegion'], 'String');
      }
      if (data.hasOwnProperty('meterName')) {
        obj['meterName'] = ApiClient.convertToType(data['meterName'], 'String');
      }
      if (data.hasOwnProperty('consumedQuantity')) {
        obj['consumedQuantity'] = ApiClient.convertToType(data['consumedQuantity'], 'Number');
      }
      if (data.hasOwnProperty('resourceRate')) {
        obj['resourceRate'] = ApiClient.convertToType(data['resourceRate'], 'Number');
      }
      if (data.hasOwnProperty('resourceLocation')) {
        obj['resourceLocation'] = ApiClient.convertToType(data['resourceLocation'], 'String');
      }
      if (data.hasOwnProperty('consumedService')) {
        obj['consumedService'] = ApiClient.convertToType(data['consumedService'], 'String');
      }
      if (data.hasOwnProperty('instanceId')) {
        obj['instanceId'] = ApiClient.convertToType(data['instanceId'], 'String');
      }
      if (data.hasOwnProperty('serviceInfo1')) {
        obj['serviceInfo1'] = ApiClient.convertToType(data['serviceInfo1'], 'String');
      }
      if (data.hasOwnProperty('serviceInfo2')) {
        obj['serviceInfo2'] = ApiClient.convertToType(data['serviceInfo2'], 'String');
      }
      if (data.hasOwnProperty('additionalInfo')) {
        obj['additionalInfo'] = ApiClient.convertToType(data['additionalInfo'], 'String');
      }
      if (data.hasOwnProperty('tags')) {
        obj['tags'] = ApiClient.convertToType(data['tags'], 'String');
      }
      if (data.hasOwnProperty('storeServiceIdentifier')) {
        obj['storeServiceIdentifier'] = ApiClient.convertToType(data['storeServiceIdentifier'], 'String');
      }
      if (data.hasOwnProperty('departmentName')) {
        obj['departmentName'] = ApiClient.convertToType(data['departmentName'], 'String');
      }
      if (data.hasOwnProperty('costCenter')) {
        obj['costCenter'] = ApiClient.convertToType(data['costCenter'], 'String');
      }
      if (data.hasOwnProperty('unitOfMeasure')) {
        obj['unitOfMeasure'] = ApiClient.convertToType(data['unitOfMeasure'], 'String');
      }
      if (data.hasOwnProperty('resourceGroup')) {
        obj['resourceGroup'] = ApiClient.convertToType(data['resourceGroup'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} serviceName
   */
  exports.prototype['serviceName'] = undefined;
  /**
   * @member {String} serviceTier
   */
  exports.prototype['serviceTier'] = undefined;
  /**
   * @member {String} location
   */
  exports.prototype['location'] = undefined;
  /**
   * @member {Boolean} chargesBilledSeparately
   */
  exports.prototype['chargesBilledSeparately'] = undefined;
  /**
   * @member {String} partNumber
   */
  exports.prototype['partNumber'] = undefined;
  /**
   * @member {String} resourceGuid
   */
  exports.prototype['resourceGuid'] = undefined;
  /**
   * @member {String} offerId
   */
  exports.prototype['offerId'] = undefined;
  /**
   * @member {Number} cost
   */
  exports.prototype['cost'] = undefined;
  /**
   * @member {Number} accountId
   */
  exports.prototype['accountId'] = undefined;
  /**
   * @member {Number} productId
   */
  exports.prototype['productId'] = undefined;
  /**
   * @member {Number} resourceLocationId
   */
  exports.prototype['resourceLocationId'] = undefined;
  /**
   * @member {Number} consumedServiceId
   */
  exports.prototype['consumedServiceId'] = undefined;
  /**
   * @member {Number} departmentId
   */
  exports.prototype['departmentId'] = undefined;
  /**
   * @member {String} accountOwnerEmail
   */
  exports.prototype['accountOwnerEmail'] = undefined;
  /**
   * @member {String} accountName
   */
  exports.prototype['accountName'] = undefined;
  /**
   * @member {String} serviceAdministratorId
   */
  exports.prototype['serviceAdministratorId'] = undefined;
  /**
   * @member {Number} subscriptionId
   */
  exports.prototype['subscriptionId'] = undefined;
  /**
   * @member {String} subscriptionGuid
   */
  exports.prototype['subscriptionGuid'] = undefined;
  /**
   * @member {String} subscriptionName
   */
  exports.prototype['subscriptionName'] = undefined;
  /**
   * @member {Date} date
   */
  exports.prototype['date'] = undefined;
  /**
   * @member {String} product
   */
  exports.prototype['product'] = undefined;
  /**
   * @member {String} meterId
   */
  exports.prototype['meterId'] = undefined;
  /**
   * @member {String} meterCategory
   */
  exports.prototype['meterCategory'] = undefined;
  /**
   * @member {String} meterSubCategory
   */
  exports.prototype['meterSubCategory'] = undefined;
  /**
   * @member {String} meterRegion
   */
  exports.prototype['meterRegion'] = undefined;
  /**
   * @member {String} meterName
   */
  exports.prototype['meterName'] = undefined;
  /**
   * @member {Number} consumedQuantity
   */
  exports.prototype['consumedQuantity'] = undefined;
  /**
   * @member {Number} resourceRate
   */
  exports.prototype['resourceRate'] = undefined;
  /**
   * @member {String} resourceLocation
   */
  exports.prototype['resourceLocation'] = undefined;
  /**
   * @member {String} consumedService
   */
  exports.prototype['consumedService'] = undefined;
  /**
   * @member {String} instanceId
   */
  exports.prototype['instanceId'] = undefined;
  /**
   * @member {String} serviceInfo1
   */
  exports.prototype['serviceInfo1'] = undefined;
  /**
   * @member {String} serviceInfo2
   */
  exports.prototype['serviceInfo2'] = undefined;
  /**
   * @member {String} additionalInfo
   */
  exports.prototype['additionalInfo'] = undefined;
  /**
   * @member {String} tags
   */
  exports.prototype['tags'] = undefined;
  /**
   * @member {String} storeServiceIdentifier
   */
  exports.prototype['storeServiceIdentifier'] = undefined;
  /**
   * @member {String} departmentName
   */
  exports.prototype['departmentName'] = undefined;
  /**
   * @member {String} costCenter
   */
  exports.prototype['costCenter'] = undefined;
  /**
   * @member {String} unitOfMeasure
   */
  exports.prototype['unitOfMeasure'] = undefined;
  /**
   * @member {String} resourceGroup
   */
  exports.prototype['resourceGroup'] = undefined;



  return exports;
}));


