/**
 * Enterprise Reporting v3 APIs (preview)
 * The Reporting APIs enable Enterprise Azure customers to programmatically pull consumption and billing data into preferred data analysis tools. Generate API Key on Enterprise portal and follow the tutorial under Help - Reporting APIs. The first section under this help article explains how to generate\\retrieve the API key for the specified enrollment. <a href=\"https://docs.microsoft.com/en-us/azure/billing/billing-enterprise-api\" data-linktype=\"external\">Billing Enterprise API official documentation</a>
 *
 * OpenAPI spec version: v3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PriceSheetV3'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/PriceSheetV3'));
  } else {
    // Browser globals (root is window)
    if (!root.EnterpriseReportingV3ApIsPreview) {
      root.EnterpriseReportingV3ApIsPreview = {};
    }
    root.EnterpriseReportingV3ApIsPreview.PriceSheetsV3Api = factory(root.EnterpriseReportingV3ApIsPreview.ApiClient, root.EnterpriseReportingV3ApIsPreview.PriceSheetV3);
  }
}(this, function(ApiClient, PriceSheetV3) {
  'use strict';

  /**
   * PriceSheetsV3 service.
   * @module api/PriceSheetsV3Api
   * @version v3
   */

  /**
   * Constructs a new PriceSheetsV3Api. 
   * @alias module:api/PriceSheetsV3Api
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the priceSheetsV3Get operation.
     * @callback module:api/PriceSheetsV3Api~priceSheetsV3GetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/PriceSheetV3>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets the price sheet for the current billing period.
     * @param {String} authorization Specify the value in this format: \&quot;bearer {API_KEY}\&quot;
     * @param {String} enrollmentNumber The enrollment number
     * @param {module:api/PriceSheetsV3Api~priceSheetsV3GetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/PriceSheetV3>}
     */
    this.priceSheetsV3Get = function(authorization, enrollmentNumber, callback) {
      var postBody = null;

      // verify the required parameter 'authorization' is set
      if (authorization === undefined || authorization === null) {
        throw new Error("Missing the required parameter 'authorization' when calling priceSheetsV3Get");
      }

      // verify the required parameter 'enrollmentNumber' is set
      if (enrollmentNumber === undefined || enrollmentNumber === null) {
        throw new Error("Missing the required parameter 'enrollmentNumber' when calling priceSheetsV3Get");
      }


      var pathParams = {
        'enrollmentNumber': enrollmentNumber
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Authorization': authorization
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json', 'text/json', 'text/html', 'application/xml', 'text/xml'];
      var returnType = [PriceSheetV3];

      return this.apiClient.callApi(
        '/v3/enrollments/{enrollmentNumber}/pricesheet', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the priceSheetsV3Get_0 operation.
     * @callback module:api/PriceSheetsV3Api~priceSheetsV3Get_0Callback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/PriceSheetV3>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get the price sheet for the provided billing period.
     * @param {String} authorization Specify the value in this format: \&quot;bearer {API_KEY}\&quot;
     * @param {String} enrollmentNumber The enrollment number
     * @param {String} billingPeriod The billing period id
     * @param {module:api/PriceSheetsV3Api~priceSheetsV3Get_0Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/PriceSheetV3>}
     */
    this.priceSheetsV3Get_0 = function(authorization, enrollmentNumber, billingPeriod, callback) {
      var postBody = null;

      // verify the required parameter 'authorization' is set
      if (authorization === undefined || authorization === null) {
        throw new Error("Missing the required parameter 'authorization' when calling priceSheetsV3Get_0");
      }

      // verify the required parameter 'enrollmentNumber' is set
      if (enrollmentNumber === undefined || enrollmentNumber === null) {
        throw new Error("Missing the required parameter 'enrollmentNumber' when calling priceSheetsV3Get_0");
      }

      // verify the required parameter 'billingPeriod' is set
      if (billingPeriod === undefined || billingPeriod === null) {
        throw new Error("Missing the required parameter 'billingPeriod' when calling priceSheetsV3Get_0");
      }


      var pathParams = {
        'enrollmentNumber': enrollmentNumber,
        'billingPeriod': billingPeriod
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Authorization': authorization
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json', 'text/json', 'text/html', 'application/xml', 'text/xml'];
      var returnType = [PriceSheetV3];

      return this.apiClient.callApi(
        '/v3/enrollments/{enrollmentNumber}/billingperiods/{billingPeriod}/pricesheet', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
