/**
 * Enterprise Reporting v3 APIs (preview)
 * The Reporting APIs enable Enterprise Azure customers to programmatically pull consumption and billing data into preferred data analysis tools. Generate API Key on Enterprise portal and follow the tutorial under Help - Reporting APIs. The first section under this help article explains how to generate\\retrieve the API key for the specified enrollment. <a href=\"https://docs.microsoft.com/en-us/azure/billing/billing-enterprise-api\" data-linktype=\"external\">Billing Enterprise API official documentation</a>
 *
 * OpenAPI spec version: v3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MarketplacePropertiesV3', 'model/ModelObject', 'model/PagedJsonDataTitaniumJuly', 'model/PriceSheetV3', 'model/RIPurchaseHistoryV3Properties', 'model/UsageDetailsDeNormalizedTitaniumJuly', 'api/MarketplacesV3Api', 'api/PriceSheetsV3Api', 'api/ReservedInstancesV3Api', 'api/UsageDetailsV3Api'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/MarketplacePropertiesV3'), require('./model/ModelObject'), require('./model/PagedJsonDataTitaniumJuly'), require('./model/PriceSheetV3'), require('./model/RIPurchaseHistoryV3Properties'), require('./model/UsageDetailsDeNormalizedTitaniumJuly'), require('./api/MarketplacesV3Api'), require('./api/PriceSheetsV3Api'), require('./api/ReservedInstancesV3Api'), require('./api/UsageDetailsV3Api'));
  }
}(function(ApiClient, MarketplacePropertiesV3, ModelObject, PagedJsonDataTitaniumJuly, PriceSheetV3, RIPurchaseHistoryV3Properties, UsageDetailsDeNormalizedTitaniumJuly, MarketplacesV3Api, PriceSheetsV3Api, ReservedInstancesV3Api, UsageDetailsV3Api) {
  'use strict';

  /**
   * The_Reporting_APIs_enable_Enterprise_Azure_customers_to_programmatically_pull_consumption_and_billing_data_into_preferred_data_analysis_tools__Generate_API_Key_on_Enterprise_portal_and_follow_the_tutorial_under_Help___Reporting_APIs__The_first_section_under_this_help_article_explains_how_to_generateretrieve_the_API_key_for_the_specified_enrollment__a_hrefhttpsdocs_microsoft_comen_usazurebillingbilling_enterprise_api_data_linktypeexternalBilling_Enterprise_API_official_documentationa.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var EnterpriseReportingV3ApIsPreview = require('index'); // See note below*.
   * var xxxSvc = new EnterpriseReportingV3ApIsPreview.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new EnterpriseReportingV3ApIsPreview.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new EnterpriseReportingV3ApIsPreview.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new EnterpriseReportingV3ApIsPreview.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version v3
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The MarketplacePropertiesV3 model constructor.
     * @property {module:model/MarketplacePropertiesV3}
     */
    MarketplacePropertiesV3: MarketplacePropertiesV3,
    /**
     * The ModelObject model constructor.
     * @property {module:model/ModelObject}
     */
    ModelObject: ModelObject,
    /**
     * The PagedJsonDataTitaniumJuly model constructor.
     * @property {module:model/PagedJsonDataTitaniumJuly}
     */
    PagedJsonDataTitaniumJuly: PagedJsonDataTitaniumJuly,
    /**
     * The PriceSheetV3 model constructor.
     * @property {module:model/PriceSheetV3}
     */
    PriceSheetV3: PriceSheetV3,
    /**
     * The RIPurchaseHistoryV3Properties model constructor.
     * @property {module:model/RIPurchaseHistoryV3Properties}
     */
    RIPurchaseHistoryV3Properties: RIPurchaseHistoryV3Properties,
    /**
     * The UsageDetailsDeNormalizedTitaniumJuly model constructor.
     * @property {module:model/UsageDetailsDeNormalizedTitaniumJuly}
     */
    UsageDetailsDeNormalizedTitaniumJuly: UsageDetailsDeNormalizedTitaniumJuly,
    /**
     * The MarketplacesV3Api service constructor.
     * @property {module:api/MarketplacesV3Api}
     */
    MarketplacesV3Api: MarketplacesV3Api,
    /**
     * The PriceSheetsV3Api service constructor.
     * @property {module:api/PriceSheetsV3Api}
     */
    PriceSheetsV3Api: PriceSheetsV3Api,
    /**
     * The ReservedInstancesV3Api service constructor.
     * @property {module:api/ReservedInstancesV3Api}
     */
    ReservedInstancesV3Api: ReservedInstancesV3Api,
    /**
     * The UsageDetailsV3Api service constructor.
     * @property {module:api/UsageDetailsV3Api}
     */
    UsageDetailsV3Api: UsageDetailsV3Api
  };

  return exports;
}));
